language: python
python:
- '3.5'
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  password:
    secure: Ck7oTEiIP1al8hE7I3E5R9/6DiWNzWv3h4ewSQfSfoqUCd5DZP/5Jh26ULFjCOCIMaBfNYrSLw6czAHrj+IctNiGFGanwHXkspeKLpHLlyZfQ9LFwocf02hygI44Pu0fMGauSA11cty717soiDff2wkc2AXeKKl9oqjsXoSuNt/7l4m7l38fK4aIXgR0LKmIMEuiiHmpbgbzqLqEM5ToI/B1hJzppDMHwhHBFhalHhvxOcCO8o7Qgo+SjxVgS6T1ojMAWoEQnLDGVhxCEG6p0zPIKEVCC2JPGne1tW+LWjOttpQGUOVquot0KAJakYRUZJbYAu+XhW8onbDinkf9/emq/gaZtxDXWutphwbveOGvWG4kuykYwl/r+c/t6gCEm3FNrPtbE0jBXcOEY61STBz3ysnRvBWfrZMxKg+KNE5i6CYSeNMf+5jOohfbs9N/A7j5PsPFJNkHQc266BIp2ProksMyIW7vY6WAq2NpywyGJkGMdhby6Drv7luGCldgp9Chpkga507fTDy2CZsTLFIWkA3cvGO+WE2fBWJNDdBrfACFpwWY3MLBQn6uO/xoCl/hDia0JLqT2HKvmjDkFP/VxL0VTuh4rHZ72vVDtbsaLRGOCnO0vBNToe66QTpFVp5w2nLoBvNNFdYltMY36WF8rLvb2FF4muMNwQ4/v7U=
