micropython -m upip install micropython-os
micropython -m upip install micropython-importlib
micropython -m upip install micropython-getopt
micropython -m upip install micropython-json
micropython -m upip install micropython-time
micropython -m upip install micropython-datetime
micropython -m upip install micropython-random
micropython -m upip install micropython-treading
micropython -m upip install micropython-traceback
micropython -m upip install micropython-types
micropython -m upip install micropython-string
micropython -m upip install kervi-core
